### ISSUE TITLE
Welcome to GitHub!

### ISSUE THREAD

**Issue by larnsce** [fairdatapub-washcentre/website#1]
# Welcome to GitHub! 🎉

Hello and welcome to GitHub. 🥳  

We're excited to have you join us. This is your first GitHub issue, and we're here to help you get started.

## What are GitHub Issues?

GitHub Issues are a tool for managing projects and collaborating with others. They serve several important purposes:

1. **Task Tracking**: Issues help us keep track of tasks.
2. **Discussions**: They provide a space for discussions about specific aspects of the project.
3. **Assignments**: We can assign issues to specific team members, making it clear who's responsible for what.
4. **Labeling**: Issues can be labeled to categorize and prioritize work.
5. **Milestones**: We can group related issues into milestones to track progress towards larger goals.

## Your First Task

To help everyone get to know each other, we'd like you to do the following:

1. **Introduce Yourself**: In the comments below, please write a brief introduction about yourself. You might include:
   - Your name
   - Your background or area of expertise
   - What interests you about openwashdata
   - A fun fact about yourself

2. **Tag Your Neighbor**: After posting your introduction, please tag the person who you sit next to using the @ symbol followed by their GitHub username. This will notify them and help build connections within our community.

Example:
```
Hi everyone! I'm Jane Doe, a software developer specializing in web technologies. 
I'm excited to contribute to this project because I love open-source collaboration. 
Fun fact: I can solve a Rubik's cube in under 2 minutes!

@larnsce , nice to meet you!
```

We look forward to getting to know you and working together on this project. Happy coding! 💻

**Comment by superGold** [comment]
Hi, I'm Randhir Rawatlal; I have a computing/modelling background. Openwashdata would establish the standards to ease data sharing and collaboration. I enjoy creating digital art!
@SueMercer

**Comment by ndlelalungi86** [comment]
Hi My name is Lungi Ndlela. I am an administrative officer in the WASH R&D Centre. 
I am eager to learn. 
@NNMhlongo glad to have you here

**Comment by DaniNaidoo** [comment]
Hey Everyone! My name is Danica Naidoo and I am a researcher specializing in One Health, and Health & Hygiene Monitoring within the WASH space. I am excited to learn more about open-source collaborations and fair data sharing, and am always keen to work with others! 

@MeganSigamoney I hope we don't get lost along the way during this workshop!

**Comment by TravisKunnen** [comment]
HI, Travis here ALL

My background is Marine biology and my area is in sanitation.
My interest is in the ease of data access. Do the hard work at 1st to make it easy later for you and all others.
I was once KO'ed by a telephone pole.

Oh, and I was the 1st to spill my drink at the table during this workshop...:)

@anurthomas89

**Comment by SueMercer** [comment]
Hi everyone - I am Sue Mercer. My background is in Chemistry but I think I do everything but Chemistry. I have been a project manager in the WASH Centre for many years. I am interested in this project as I worry about all our data being lost. Fun fact: I backpacked around Europe for a year in 1990 @superGold

**Comment by MeganSigamoney** [comment]
Hi everyone. My name is Megan Sigamoney and I have a MSc in Biological Science. I am a research scientist at the WASH R&D Centre with a focus on human and plant health in water and sanitation. 
I enjoy sketching and creating art. 
@DaniNaidoo I am happy to be sitting next to you as we navigate this workshop!

**Comment by PreyanA26** [comment]
Greetings All, my name is Preyan Arumugam and I am sanitation geek. My interest is the sharing of data for the sound and informed decision making.

Fun fact: I have many addictions  @MeganSigamoney

**Comment by MbolekwaE** [comment]
My name is Eddie Mbolekwa, Admin Officer at WASH R&D Centre. I hoping to contribute to the growth of the Centre and I hope this can help me in doing that.

@SGetahun i hope you surviving so far

**Comment by IBanoo** [comment]
Hi Ismail Banoo. I have a water and environmental research background. I would like to learn more about Openwash data stewardship and management. 

@anurthomas89

**Comment by anurthomas89** [comment]
Hi everyone! I'm a postdoctoral researcher at WASH R&D Centre, UKZN. I'm eager to learn about data management and looking forward to the openwashdata project. Funfact: i don't know swimming. 
@IBanoo @TravisKunnen @philpk-WASH @PreyanA26

**Comment by philpk-WASH** [comment]
Kerry Philp.
Research admin and finance
Some understanding of data management is critical to survive in this world
I friggin love pigeons! I think I should do a seminar on them :-)
@mbolekwae

**Comment by V-Po-V** [comment]
Hi everyone. I'm Leesan Naidoo, a student researching sensors for measuring water quality. I'm interested in learning about the accessibility of open-source data sharing. I enjoy reading murder mysteries. @XabelaS

**Comment by NNMhlongo** [comment]
Hi everyone, My name is Novuyo Mhlongo,  i am a chemical engineering Intern at Wash R&D Centre. I work with solar dryers I am based in Newlands.

**Comment by SGetahun** [comment]
Hello. My name is Samuel Getahun. I am chemical engineer by training working in the WASH sector as a researcher
Im Interested in about openwashdata due to the possibility of sharing the data from my current and previous research output for a better future in the sector and increase my visibility.

**Comment by MbolekwaE** [comment]
The fun fact about me is i am not fun

**Comment by XabelaS** [comment]
Hi everyone, I am Sinethemba Xabela, a postdoctoral student at WASH CENTRE, UKZN, specializing membrane technology, nanomaterials, and water treatment. I enjoy working on research project that address water related issues. Fun fact: I hate travelling.

**Comment by Bentono** [comment]
@XabelaS welcome.

**Comment by rainbow-train** [comment]
> Hi everyone, My name is Novuyo Mhlongo, i am a chemical engineering Intern at Wash R&D Centre. I work with solar dryers I am based in Newlands.

Quote

**Comment by SGetahun** [comment]
> The fun fact about me is i am not fun

True :)

**Comment by nonhlelo-art** [comment]
Greetings to all, my name is Nonhlelo Kunene, and I am a civil engineering technologist with a specialization in water engineering. I work on GIS and climate resilience related projects. 

Fun fact: I'm hanging somewhere in the room.

**Comment by philpk-WASH** [comment]
> Hi everyone, I am Sinethemba Xabela, a postdoctoral student at WASH CENTRE, UKZN, specializing membrane technology, nanomaterials, and water treatment. I enjoy working on research project that address water related issues. Fun fact: I hate travelling.

Sne I'm with you on that - travelling is overrated
